# Generated by Django 3.2.9 on 2021-12-03 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instapp', '0004_auto_20211203_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='user',
        ),
    ]
