# Generated by Django 3.2.9 on 2021-12-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instapp', '0014_auto_20211207_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='value',
            field=models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='like', max_length=10),
        ),
    ]
